### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Simple205** [SmushyTaco/Legacy-Display#1]
I really like this mod so far and there could be a lot of cool things added to it so I've compiled some of my ideas for it and I hope some of them can be added.

**Alpha title screen.** 
For the alpha title screen the animated stone blocks that drop into letters would be pretty cool and add a lot to the alpha experience.
1.16 Legacy Display
![image](https://user-images.githubusercontent.com/73256738/117560627-6b164200-b05d-11eb-9fda-dc7f6068b7d5.png)

Alpha 1.2.3
![image](https://user-images.githubusercontent.com/73256738/117560711-158e6500-b05e-11eb-802d-d33fd941da67.png)

**beta title screen**
Not much to say about this except that the buttons were obviously different back then and the appearance of the logo could easily be changed with a resource pack.

1.16 Legacy Display
![image](https://user-images.githubusercontent.com/73256738/117560626-694c7e80-b05d-11eb-8afb-420ff133948f.png)

Beta 1.7.3
![image](https://user-images.githubusercontent.com/73256738/117560648-b2043780-b05d-11eb-863b-86745269d1d0.png)

**Loading Screen**
I think this one is pretty self explanatory 
Mojang Specifications loading screen for alpha and for the beta one the big orange Mojang logo 

Beta
![image](https://user-images.githubusercontent.com/73256738/117560402-77010480-b05b-11eb-960f-5a642ab201a1.png)

Alpha
![image](https://user-images.githubusercontent.com/73256738/117560418-8718e400-b05b-11eb-8c7a-68313e1b2f1e.png)

**Consistency**
Best issue for last! There are a lot of differences between the classic title screen and the modern one I will be listing some suggestions to fix it. (by classic I mean the menu from b1.7.3) 

- The game version in beta was located in the top left corner of the menu and was colored dark grey, the modern menu is colored white and in the bottom left corner.
- There were less buttons in the classic title with a different layout than the current one, The problem with this is not being able to access some features since Minecraft realms and the mod menu isn't in beta, To fix this relocate the buttons somewhere else to accommodate the classic title screen.
**Options Menu**
The classic options, controls, and video settings menus were also much simpler the problem with this is the amount of features and options that have been added over the years and a fair solution would be to add an advanced options tab under the classic one.  

1.16
![image](https://user-images.githubusercontent.com/73256738/117560945-656e2b80-b060-11eb-93ea-000c26873a45.png)

b1.7.3
![image](https://user-images.githubusercontent.com/73256738/117560992-abc38a80-b060-11eb-823e-3f1cdd73a336.png)

**Concepts** 
Classic title screen layout with Minecraft realms, language and accessibility options tab added
![image](https://user-images.githubusercontent.com/73256738/117561577-04e1ed00-b066-11eb-86a9-c570c4d0fa03.png)

Options menu, Advanced options and mod menu buttons added 
![image](https://user-images.githubusercontent.com/73256738/117561617-46729800-b066-11eb-8a4f-d8b1ee053195.png)

These are only photoshopped concepts, I couldn't code a mod if my life depended on it.

I hope that these suggestions are taken into consideration and at least some of these features get added, even if not this is still a pretty damn fine mod for what it is and I love the world loading screen!

**Comment by SmushyTaco** [comment]
I'd love to change the GUI to make it look like the older versions but the issue with that sadly is that it would cause a lot of issues with mods that add GUI elements (Overlapping buttons, buttons from other mods not showing up, and who knows what else could happen) which is why I chose not to tackle the task of doing so. Regarding the launching screen that can be changed with a resource pack from what I know (Maybe not with vanilla Minecraft but there are mods that allow it) and if not then I'd have to redistribute Mojang's older textures for the loading screen which could be a very grey area I'd rather not get into. I wish I could implement all of this but if I did I'd be constantly working on mod compatibility that would constantly break by other newly released mods (and possibly by newer Minecraft versions too but that's not that much of an issue).

P.S. I'm glad you like the world loading screen! That's my favorite part of the mod too.
